### ISSUE TITLE
Can we turn off spell check?

### ISSUE THREAD

**Issue by hgputnam** [UCSF-CBI/c4#1]
Doing the documentation we use lots of non-english invented words (pwd, cwd, ls, etc) that will not pass the spell checker. Can that be turned off?

**Comment by HenrikBengtsson** [comment]
Instead, add the "unknown" words to the [`docs/WORDLIST`](https://github.com/UCSF-CBI/c4/blob/master/docs/WORDLIST).

If you install R and the required packages as explained in the [README](https://github.com/UCSF-CBI/c4/blob/master/README.md), you can also check it locally:

```sh
$ cd docs/
$ make spell
  WORD     FOUND IN
cwd      hello-world-job.md:67
         hello-world-job.md:67
sbatch   hello-world-job.md:20,67
         hello-world-job.md:20,67
slurm    hello-world-job.md:67
         hello-world-job.md:67
Makefile:62: recipe for target 'spell' failed
make: *** [spell] Error 1
```

OTH, I should probably updated the spell checker to use `aspell` or something since it's easier to install.

**Comment by HenrikBengtsson** [comment]
I've added the misisng words

**Comment by hgputnam** [comment]
I managed to reverse engineer `make check` enough to get the r spelling package running on my vm where I like to do the git updates. Is the dictionary file something I can check out and update with git so that the spell check would pass on my local vm and on github?

**Comment by hgputnam** [comment]
Oh OK I see, do that with docs/WORDLIST. Ok that should work.
