### ISSUE TITLE
Module command not found

### ISSUE THREAD

**Issue by piaolabucsf** [UCSF-CBI/c4#46]
Hi! I just opened my account on the C4 cluster, and when I type "module load CBI", I got an error message as "module: command not found". May I ask how to fix this issue? Thanks!

**Comment by HenrikBengtsson** [comment]
Hi.  I suspect you're trying this on a login or a data-transfer node.  **The module system is only available on the development and compute nodes**.  FWIW, this is mentioned in the 'Summary of Compute Environment' table on https://ucsf-cbi.github.io/c4/about/specs.html.

---

Looking at https://ucsf-cbi.github.io/c4/software/software-modules.html and https://ucsf-cbi.github.io/c4/software/software-repositories.html, I see that this is not clear.  There's a sentence hidden in there saying "Since module is only available on the development and compute nodes, ..." but that's all.  I'll add it to my to-do list to improve this.

**Comment by HenrikBengtsson** [comment]
Oh... I just noticed that you posted this to the issue tracker of the website per se.  In the future, please use the dedicated tracker mentioned on https://ucsf-cbi.github.io/c4/support/ for support issues.
