### ISSUE TITLE
Need help with python and R pages.

### ISSUE THREAD

**Issue by hgputnam** [UCSF-CBI/c4#6]
I am unqualified to edit the python and R pages. They look right but I wouldn't know the difference.

**Comment by HenrikBengtsson** [comment]
I can update those.

PS. Lots of that output is dynamically generated so that the Python/R output can be kept up-to-date automatically with little manual intervention.  I doing this as a test/prototype to see if it is helpful - it could turn out that it's just too much work. If so, I'll roll it back to basic cut'n'pasted Markdown info.

**Comment by hgputnam** [comment]
Thanks, I'm sure to find more stuff I don't know much about. Let me know next time you teach an R class (for Dummies hopefully). I will definitely sign up...

**Comment by HenrikBengtsson** [comment]
I've re-generated the Python and R examples.
