### ISSUE TITLE
Higlass remote integration to c4

### ISSUE THREAD

**Issue by dgoekbuget** [UCSF-CBI/c4#70]
Hi,

I was wondering if the c4 cluster has a SOP for using higlass remotely similar to how we can use R studio?
https://docs.higlass.io/higlass_docker.html
I think it would be helpful to have at least one good way to visualize HiC data using the cluster.
Best,

Deniz

**Comment by hgputnam** [comment]
Hi Deniz - We have to be very strategic about which platforms we support in this way with OnDemand, rstudio-server-controller, etc. because we have very limited staff to support the cluster. We cannot take on any new Rstudio grade projects. Having said that, you are certainly free to make higlass work yourself. Docker is not allowed on C4 since it requires root access but if you can convert the docker container to singularity then the cluster will be able to run it. Our development servers are there for just this sort of work. If you do go down that path, I encourage you to share what you learn here and on Slack since others might be interested. 

Our C4 specific singularity doc is here: https://www.c4.ucsf.edu/software/singularity.html Singularity is also very well documented here: https://docs.sylabs.io/guides/3.5/user-guide/introduction.html

For some types of container builds, you need sudo to make things work. I can't give you sudo on the cluster but we do have a build host (a disposable VM) for that sort of thing.  It is not part of the cluster so no shared storage but other Labs have been able to do builds there and make things work. Let me know if you need access to it.
